/**
 * NOTE:
 *
 * In this module, "endnote" refers to notes collected at the end of the
 * document as generated by mdast-util-to-hast, while "footnote" refers to
 * notes that float to the bottom of each page as defined by
 * [css-gcpm](https://www.w3.org/TR/css-gcpm-3/#footnotes).
 * This does not match the export names or attribute naming used by remark.
 *
 * Terminology follows css-gcpm: a "call" is the in-text reference showing the
 * note number, a "marker" is the note number rendered in the footnote area,
 * an "element" is the note content, a "body" is the marker and element
 * combined, and an "area" is the region where notes are collected for display.
 *
 * VFM depends on two versions of mdast-util-to-hast:
 *  `- remark-rehype@8.1.0
 *  |   `- mdast-util-to-hast@10.2.0  <-- endnote generation (internal)
 *  `- mdast-util-to-hast@11.3.0      <-- Handler type & all() (direct import)
 */

import {
  createDpubFootnotePlugin,
  DpubFootnoteOptionsSchema,
  DpubYamlFootnoteOptionsSchema,
  type DpubFootnoteOptions,
} from '@vivliostyle/remark-footnote-dpub';
import {
  createGcpmFootnotePlugin,
  GcpmFootnoteOptionsSchema,
  GcpmYamlFootnoteOptionsSchema,
  type GcpmFootnoteOptions,
} from '@vivliostyle/remark-footnote-gcpm';
import {
  createPandocFootnotePlugin,
  PandocFootnoteOptionsSchema,
} from '@vivliostyle/remark-footnote-pandoc';
import type { Handler as ToHastHandler } from 'mdast-util-to-hast';
import footnotes from 'remark-footnotes';
import type unified from 'unified';
import * as v from 'valibot';
import { partial } from '../utils.js';

// Re-export factory types so vfm consumers (and the index.ts re-exports)
// keep their existing import paths.
export type {
  DpubCallFactory,
  DpubBodyFactory,
  DpubBodyChildren,
  DpubCallChildren,
  FootnoteFactory as DpubFootnoteFactory,
} from '@vivliostyle/remark-footnote-dpub';
export type {
  GcpmBodyFactory,
  GcpmDuplicatedCallFactory,
  FootnoteFactory as GcpmFootnoteFactory,
} from '@vivliostyle/remark-footnote-gcpm';

/**
 * - `"pandoc"`: endnote section at document end (default).
 * - `"dpub"`: `<a role="doc-noteref">` calls with `<aside role="doc-footnote">`
 *   elements placed after the containing block element.
 * - `"gcpm"`: inline `<span class="footnote">` at the call site.
 */
export type FootnoteMode = 'pandoc' | 'dpub' | 'gcpm';

export const FootnoteModeSchema = v.union([
  v.literal('pandoc'),
  v.literal('dpub'),
  v.literal('gcpm'),
]);

export const FootnoteOptionsSchema = v.object({
  footnote: v.optional(
    v.union([
      FootnoteModeSchema,
      v.variant('mode', [
        PandocFootnoteOptionsSchema,
        DpubFootnoteOptionsSchema,
        GcpmFootnoteOptionsSchema,
      ]),
    ]),
  ),
});

export type FootnoteOptions = v.InferInput<typeof FootnoteOptionsSchema>;

/**
 * YAML-safe variant of {@link FootnoteOptionsSchema}: customizer fields
 * accept `hast.Properties` only, since YAML cannot represent JavaScript
 * functions.
 */
export const YamlFootnoteOptionsSchema = v.object({
  footnote: v.optional(
    v.union([
      FootnoteModeSchema,
      v.variant('mode', [
        PandocFootnoteOptionsSchema,
        DpubYamlFootnoteOptionsSchema,
        GcpmYamlFootnoteOptionsSchema,
      ]),
    ]),
  ),
});

export type YamlFootnoteOptions = v.InferInput<
  typeof YamlFootnoteOptionsSchema
>;

type ResolvedOption =
  | { mode: 'pandoc' }
  | DpubFootnoteOptions
  | GcpmFootnoteOptions;

const resolveOption = (opt: FootnoteOptions['footnote']): ResolvedOption => {
  if (!opt) {
    return { mode: 'pandoc' };
  }
  if (typeof opt === 'string') {
    return { mode: opt };
  }
  return opt;
};

/**
 * Handlers returned by `createFootnotePlugin` for each footnote-related mdast
 * node type. A value of `undefined` means "fall through to
 * mdast-util-to-hast's default handler"; consumers are responsible for
 * omitting undefined entries when merging into remark-rehype's `handlers`
 * option (explicit undefined would otherwise overwrite the default).
 */
export type FootnoteToHastHandlers = {
  footnoteDefinition: ToHastHandler | undefined;
  footnoteReference: ToHastHandler | undefined;
  footnote: ToHastHandler | undefined;
};

export const createFootnotePlugin = (
  options?: FootnoteOptions,
): {
  toHastHandlers: FootnoteToHastHandlers;
  hastTransformer: unified.Plugin;
} => {
  const resolved = resolveOption(options?.footnote);

  if (resolved.mode === 'pandoc') {
    return createPandocFootnotePlugin();
  }

  if (resolved.mode === 'dpub') {
    return createDpubFootnotePlugin(resolved);
  }

  return createGcpmFootnotePlugin(resolved);
};

/**
 * Process Markdown AST.
 */
export const mdast = partial(footnotes, { inlineNotes: true });
