/**
 * NOTE:
 *
 * In this module, "endnote" refers to notes collected at the end of the
 * document as generated by mdast-util-to-hast, while "footnote" refers to
 * notes that float to the bottom of each page as defined by
 * [css-gcpm](https://www.w3.org/TR/css-gcpm-3/#footnotes).
 * This does not match the export names or attribute naming used by remark.
 *
 * Terminology follows css-gcpm: a "call" is the in-text marker showing the
 * note number, an "element" is the note content itself, and an "area" is the
 * region where notes are collected for display.
 *
 * VFM depends on two versions of mdast-util-to-hast:
 *  `- remark-rehype@8.1.0
 *  |   `- mdast-util-to-hast@10.2.0  <-- endnote generation (internal)
 *  `- mdast-util-to-hast@11.3.0      <-- Handler type & all() (direct import)
 */

import type * as hast from 'hast';
import { selectAll } from 'hast-util-select';
import { h } from 'hastscript';
import {
  type Handler as ToHastHandler,
  all as convertToHast,
} from 'mdast-util-to-hast';
import footnotes from 'remark-footnotes';
import type unified from 'unified';
import { u } from 'unist-builder';

type ElementWithProps = hast.Element & {
  properties: NonNullable<hast.Element['properties']>;
};

/**
 * @see https://github.com/syntax-tree/mdast-util-to-hast/blob/10.2.0/lib/footer.js#L55-L66
 */
const endnoteAreaSelector = 'div.footnotes';
type EndnoteArea = hast.Element & {
  tagName: 'div';
  properties: { className: ['footnotes'] };
};
const selectEndnoteAreas = (tree: hast.Root) =>
  selectAll(endnoteAreaSelector, tree) as EndnoteArea[];

/**
 * @see https://github.com/syntax-tree/mdast-util-to-hast/blob/10.2.0/lib/footer.js#L43-L48
 */
const endnoteElementSelector = `${endnoteAreaSelector} ol li[id^="fn-"]`;
type EndnoteElement = hast.Element & {
  tagName: 'li';
  properties: { id: `fn-${string}` };
};
const selectEndnoteElements = (tree: hast.Root) =>
  selectAll(endnoteElementSelector, tree) as EndnoteElement[];

/**
 * @see https://github.com/syntax-tree/mdast-util-to-hast/blob/10.2.0/lib/handlers/footnote-reference.js#L15-L19
 */
const endnoteCallSelector =
  'sup[id^="fnref-"]:has(a:only-child[href^="#fn-"].footnote-ref)';
type EndnoteCall = hast.Element & {
  tagName: 'sup';
  properties: { id: `fnref-${string}` };
  children: [
    hast.Element & {
      tagName: 'a';
      properties: {
        href: `#${string}`;
        className: ['footnote-ref'];
      };
    },
  ];
};
const selectEndnoteCalls = (tree: hast.Root) =>
  selectAll(endnoteCallSelector, tree) as EndnoteCall[];

/**
 * @see https://github.com/syntax-tree/mdast-util-to-hast/blob/10.2.0/lib/footer.js#L29-L34
 */
const endnoteBackReferenceSelector = 'a.footnote-backref';
type EndnoteBackReference = hast.Element & {
  tagName: 'a';
  properties: { className: ['footnote-backref'] };
};
const selectEndnoteBackReferences = (parent: hast.Element) =>
  selectAll(endnoteBackReferenceSelector, parent) as EndnoteBackReference[];

/**
 * Transform the endnote link with Pandoc format.
 */
const endnoteCallsToPandoc: unified.Plugin = () => (tree) => {
  selectEndnoteCalls(tree as hast.Root).forEach((call, i) => {
    const sup: ElementWithProps = call;
    const [anchor]: [ElementWithProps] = call.children;

    const refIndex = i + 1;

    // Mutate sup into <a class="footnote-ref">
    sup.tagName = 'a';
    sup.properties = {
      id: `fnref${refIndex}`,
      href: `#fn${refIndex}`,
      className: ['footnote-ref'],
      role: 'doc-noteref',
    };

    // Mutate anchor into <sup>N</sup>
    anchor.tagName = 'sup';
    anchor.properties = {};
    anchor.children = [u('text', `${refIndex}`)];
  });
};

/**
 * Transform the endnote with Pandoc format.
 */
const endnoteAreasToPandoc: unified.Plugin = () => (tree) => {
  const root = tree as hast.Root;

  // must be called before mutating area.tagName
  const endnoteElements = selectEndnoteElements(root);

  selectEndnoteAreas(root).forEach((area: ElementWithProps) => {
    area.tagName = 'section';
    area.properties.role = 'doc-endnotes';
  });

  endnoteElements.forEach((elem: ElementWithProps, i) => {
    const refIndex = i + 1;

    elem.properties.id = `fn${refIndex}`;
    elem.properties.role = 'doc-endnote';

    // Back reference is expected to be placed at the end of contents
    // @see https://github.com/syntax-tree/mdast-util-to-hast/blob/10.2.0/lib/footer.js#L41
    selectEndnoteBackReferences(elem).forEach((backref: ElementWithProps) => {
      backref.properties.href = `#fnref${refIndex}`;
      backref.properties.className = ['footnote-back'];
      backref.properties.role = 'doc-backlink';
    });
  });
};

/**
 * Factory that customizes a footnote element. The returned element's
 * `tagName` is ignored: the caller forces the appropriate tag
 * (`<span>` for gcpm, `<a>` / `<aside>` for dpub).
 * @template TProps Structural properties provided by the caller.
 */
export type FootnoteFactory<TProps> = (
  h: typeof import('hastscript').h,
  properties: TProps,
  children: hast.ElementContent[],
) => Omit<hast.Element, 'tagName'>;

/**
 * - `"pandoc"`: endnote section at document end (default).
 * - `"dpub"`: `<a role="doc-noteref">` calls with `<aside role="doc-footnote">`
 *   elements placed after the containing block element.
 * - `"gcpm"`: inline `<span class="footnote">` at the call site.
 */
export type FootnoteMode = 'pandoc' | 'dpub' | 'gcpm';

export type FootnoteOptions = {
  footnote?:
    | FootnoteMode
    | { mode: 'pandoc' }
    | {
        mode: 'dpub';
        call?:
          | hast.Properties
          | FootnoteFactory<{
              id: string;
              href: string;
              role: 'doc-noteref';
            }>;
        element?:
          | hast.Properties
          | FootnoteFactory<{ id: string; role: 'doc-footnote' }>;
      }
    | {
        mode: 'gcpm';
        element?: hast.Properties | FootnoteFactory<{ id: string }>;
      };
};

type BuildFootnote = (
  id: string,
  children: hast.ElementContent[],
) => hast.Element;

const createBuildFootnote =
  (factory: FootnoteFactory<{ id: string }>): BuildFootnote =>
  (id, children) => {
    const result = factory(h, { id }, children);
    (result as hast.Element).tagName = 'span';
    return result as hast.Element;
  };

const createInlineFootnoteHandler =
  (buildFootnote: BuildFootnote): ToHastHandler =>
  (ctx, node) => {
    let no = 1;
    while (String(no) in ctx.footnoteById) {
      no++;
    }
    const identifier = String(no);
    ctx.footnoteById[identifier] = {
      type: 'footnoteDefinition',
      identifier,
      children: [{ type: 'paragraph', children: node.children }],
      position: node.position,
    };
    return buildFootnote(`fn-${identifier}`, convertToHast(ctx, node));
  };

const createFootnoteReferenceHandler =
  (buildFootnote: BuildFootnote): ToHastHandler =>
  (ctx, node) => {
    const identifier = String(node.identifier);
    const def = ctx.footnoteById[identifier.toUpperCase()];
    return !def
      ? null
      : buildFootnote(
          `fn-${identifier}`,
          convertToHast(
            ctx,
            // Unwrap single-paragraph definitions to produce inline content
            // (matches tight list-item behavior in footer.js).
            def.children.length === 1 && def.children[0].type === 'paragraph'
              ? def.children[0]
              : def,
          ),
        );
  };

/**
 * Build a hast element by applying a Properties-or-Factory customizer.
 * The caller provides the fixed `tagName` and `structuralProps`;
 * user-supplied Properties are spread after structural ones (user wins).
 * For Factory, the factory receives structural props and its returned
 * properties are merged with structural props winning only for `tagName`.
 */
const buildElement = <TProps extends hast.Properties>(
  tagName: string,
  structuralProps: TProps,
  children: hast.ElementContent[],
  customizer: hast.Properties | FootnoteFactory<TProps> | undefined,
): hast.Element => {
  if (typeof customizer === 'function') {
    const result = customizer(h, structuralProps, children);
    (result as hast.Element).tagName = tagName;
    return result as hast.Element;
  }
  if (typeof customizer === 'object') {
    return h(tagName, { ...structuralProps, ...customizer }, ...children);
  }
  return h(tagName, structuralProps, ...children);
};

/**
 * Create mdast-to-hast handlers and hast transformers for footnote processing.
 *
 * When `footnote` is `"pandoc"` or unset (default):
 * - `toHastHandlers` is empty; the default mdast-util-to-hast handlers
 *   generate endnote sections.
 * - `hastTransformers` rewrites the endnote markup to Pandoc format.
 *
 * When `footnote` is `"gcpm"`:
 * - `toHastHandlers` provides custom `footnoteReference` and `footnote`
 *   handlers that produce `<span>` footnote elements at the call site.
 *
 * When `footnote` is `"dpub"`:
 * - `toHastHandlers` produces `<a role="doc-noteref">` calls and queues
 *   `<aside role="doc-footnote">` elements for insertion.
 * - `hastTransformers` inserts aside elements after the nearest
 *   non-flow-container ancestor.
 *
 * @param options Footnote options.
 * @returns `toHastHandlers` for remark-rehype and `hastTransformers` as
 *   unified plugins to be spread into the pipeline.
 */
const createDpubFootnoteReferenceHandler =
  (
    pending: Map<string, hast.Element>,
    nextIndex: () => number,
    callCustomizer:
      | hast.Properties
      | FootnoteFactory<{ id: string; href: string; role: 'doc-noteref' }>
      | undefined,
    elementCustomizer:
      | hast.Properties
      | FootnoteFactory<{ id: string; role: 'doc-footnote' }>
      | undefined,
  ): ToHastHandler =>
  (ctx, node) => {
    const identifier = String(node.identifier);
    const def = ctx.footnoteById[identifier.toUpperCase()];
    if (!def) {
      return null;
    }

    const refIndex = nextIndex();
    const callId = `fnref${refIndex}`;
    const fnId = `fn${refIndex}`;

    pending.set(
      callId,
      buildElement(
        'aside',
        { id: fnId, role: 'doc-footnote' as const },
        convertToHast(
          ctx,
          def.children.length === 1 && def.children[0].type === 'paragraph'
            ? def.children[0]
            : def,
        ),
        elementCustomizer,
      ),
    );

    return buildElement(
      'a',
      { id: callId, href: `#${fnId}`, role: 'doc-noteref' as const },
      [u('text', `${refIndex}`)],
      callCustomizer,
    );
  };

const createDpubInlineFootnoteHandler =
  (
    pending: Map<string, hast.Element>,
    nextIndex: () => number,
    callCustomizer:
      | hast.Properties
      | FootnoteFactory<{ id: string; href: string; role: 'doc-noteref' }>
      | undefined,
    elementCustomizer:
      | hast.Properties
      | FootnoteFactory<{ id: string; role: 'doc-footnote' }>
      | undefined,
  ): ToHastHandler =>
  (ctx, node) => {
    let no = 1;
    while (String(no) in ctx.footnoteById) {
      no++;
    }
    const identifier = String(no);
    ctx.footnoteById[identifier] = {
      type: 'footnoteDefinition',
      identifier,
      children: [{ type: 'paragraph', children: node.children }],
      position: node.position,
    };

    const refIndex = nextIndex();
    const callId = `fnref${refIndex}`;
    const fnId = `fn${refIndex}`;

    pending.set(
      callId,
      buildElement(
        'aside',
        { id: fnId, role: 'doc-footnote' as const },
        convertToHast(ctx, node),
        elementCustomizer,
      ),
    );

    return buildElement(
      'a',
      { id: callId, href: `#${fnId}`, role: 'doc-noteref' as const },
      [u('text', `${refIndex}`)],
      callCustomizer,
    );
  };

/**
 * Elements that accept flow content as children, into which aside
 * insertion recurses to find a more precise insertion point.
 * For all other elements the aside is placed immediately after the
 * element in its parent.
 *
 * Transparent elements are included because this set is only consulted
 * from within a flow container context, so they inherit flow content
 * model from their parent.
 * @see https://html.spec.whatwg.org/multipage/dom.html#flow-content
 * @see https://html.spec.whatwg.org/multipage/dom.html#transparent-content-models
 */
const flowContainerTagNames = new Set([
  'address',
  'article',
  'aside',
  'blockquote',
  'body',
  'dd',
  'details',
  'dialog',
  'div',
  'fieldset',
  'figcaption',
  'figure',
  'footer',
  'form',
  'header',
  'li',
  'main',
  'nav',
  'search',
  'section',
  'td',
  'th',
  // Transparent content model
  'a',
  'audio',
  'canvas',
  'del',
  'ins',
  'map',
  'object',
  'slot',
  'video',
]);

/**
 * Insert each pending aside after the nearest non-flow-container
 * ancestor of its call element.
 */
const createInsertDpubAsides =
  (pending: Map<string, hast.Element>): unified.Plugin =>
  () =>
  (tree) => {
    if (pending.size === 0) {
      return;
    }

    const remaining = new Set(pending.keys());

    function containsCall(
      node: hast.RootContent | hast.ElementContent,
    ): string[] {
      if (remaining.size === 0 || node.type !== 'element') {
        return [];
      }
      const id = node.properties?.id;
      return [
        ...(typeof id === 'string' && remaining.has(id) ? [id] : []),
        ...node.children.flatMap((child) => containsCall(child)),
      ];
    }

    function processParent(parent: hast.Element | hast.Root) {
      const newChildren: (hast.RootContent | hast.ElementContent)[] = [];
      for (const child of parent.children) {
        newChildren.push(child);
        if (child.type !== 'element') {
          continue;
        }
        if (flowContainerTagNames.has(child.tagName)) {
          processParent(child);
        } else {
          for (const callId of containsCall(child)) {
            const aside = pending.get(callId);
            if (aside) {
              newChildren.push(aside);
              remaining.delete(callId);
            }
          }
        }
      }
      parent.children = newChildren;
    }

    const root = tree as hast.Root;
    processParent(root);

    for (const callId of remaining) {
      const aside = pending.get(callId);
      if (aside) {
        root.children.push(aside);
      }
    }
  };

type ResolvedOption =
  | { mode: 'pandoc' }
  | {
      mode: 'dpub';
      call?:
        | hast.Properties
        | FootnoteFactory<{ id: string; href: string; role: 'doc-noteref' }>;
      element?:
        | hast.Properties
        | FootnoteFactory<{ id: string; role: 'doc-footnote' }>;
    }
  | {
      mode: 'gcpm';
      element?: hast.Properties | FootnoteFactory<{ id: string }>;
    };

const resolveOption = (opt: FootnoteOptions['footnote']): ResolvedOption => {
  if (!opt) {
    return { mode: 'pandoc' };
  }
  if (typeof opt === 'string') {
    return { mode: opt };
  }
  return opt;
};

export const createFootnotePlugin = (
  options?: FootnoteOptions,
): {
  toHastHandlers: Record<'footnoteReference' | 'footnote', ToHastHandler> | {};
  hastTransformers: unified.PluggableList;
} => {
  const resolved = resolveOption(options?.footnote);

  if (resolved.mode === 'pandoc') {
    return {
      toHastHandlers: {},
      hastTransformers: [endnoteCallsToPandoc, endnoteAreasToPandoc],
    };
  }

  if (resolved.mode === 'dpub') {
    const pending = new Map<string, hast.Element>();
    let counter = 0;
    const nextIndex = () => ++counter;
    return {
      toHastHandlers: {
        footnoteReference: createDpubFootnoteReferenceHandler(
          pending,
          nextIndex,
          resolved.call,
          resolved.element,
        ),
        footnote: createDpubInlineFootnoteHandler(
          pending,
          nextIndex,
          resolved.call,
          resolved.element,
        ),
      },
      hastTransformers: [createInsertDpubAsides(pending)],
    };
  }

  // gcpm
  const element = resolved.element;
  const buildFootnote = createBuildFootnote(
    typeof element === 'function'
      ? element
      : typeof element === 'object'
      ? (hFn, props, children) =>
          hFn('span', { ...props, ...element }, ...children)
      : (hFn, props, children) =>
          hFn('span', { class: 'footnote', ...props }, ...children),
  );

  return {
    toHastHandlers: {
      footnoteReference: createFootnoteReferenceHandler(buildFootnote),
      footnote: createInlineFootnoteHandler(buildFootnote),
    },
    hastTransformers: [],
  };
};

/**
 * Process Markdown AST.
 */
export const mdast = [footnotes, { inlineNotes: true }];
